create table songs(
   sid INTEGER  NOT NULL PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   artist VARCHAR(255) NOT NULL,
   album VARCHAR(255) NOT NULL,
   year INTEGER  NOT NULL,
   durationsec INTEGER NOT NULL
);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (101,'Running Up That Hill (A Deal With God)','Kate Bush','Hounds Of Love',2019,235);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (102,'As It Was','Harry Styles','As It Was',2014,246);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (103,'Sunroof','Nicky Youre','Sunroof',2011,176);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (104,'Heat Waves','Glass Animals','Dreamland (+ Bonus Levels)',2014,238);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (105,'About Damn Time','Lizzo','About Damn Time',2018,296);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (106,'Glimpse of Us','Joji','Glimpse of Us',2013,187);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (107,'Bad Habit','Steve Lacy','Gemini Rights',2012,241);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (108,'STAY (with Justin Bieber)','The Kid LAROI','STAY (with Justin Bieber)',2017,282);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (109,'Enemy (with JID) - from the series Arcane League of Legends','Imagine Dragons','Enemy (with JID) [from the series Arcane League of Legends]',2015,187);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (110,'First Class','Jack Harlow','First Class',2014,184);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (111,'Afraid To Feel','LF SYSTEM','Afraid To Feel',2013,267);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (112,'Betty (Get Money)','Yung Gravy','Betty (Get Money)',2020,179);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (113,'abcdefu','GAYLE','abcdefu',2018,288);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (114,'Being Good Is Boring','Jena Rose','Being Good Is Boring',2017,280);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (115,'MIDDLE OF THE NIGHT','Elley Duhé','MIDDLE OF THE NIGHT',2018,168);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (116,'Envolver','Anitta','Envolver',2011,241);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (117,'AMG','Jt5k','AMG',2019,261);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (118,'SNAP','Rosa Linn','SNAP',2020,210);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (119,'Baby Girl','Disco Lines','Baby Girl',2020,212);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (120,'Flex On My Ex (with Bankrol Hayden)','KillBunk','Flex On My Ex (with Bankrol Hayden)',2016,228);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (121,'House of Memories','Panic! At The Disco','Death of a Bachelor',2017,222);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (122,'The Plan','Arman Aydin','The Plan',2019,162);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (123,'Thousand Miles','The Kid LAROI','Thousand Miles',2015,161);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (124,'INDUSTRY BABY (feat. Jack Harlow)','Lil Nas X','INDUSTRY BABY (feat. Jack Harlow)',2013,232);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (125,'Until I Found You','Stephen Sanchez','Until I Found You',2018,180);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (126,'Oh No','Kreepa','Cold As Ice',2010,189);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (127,'Cooped Up (with Roddy Ricch)','Post Malone','Cooped Up',2014,185);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (128,'TO THE MOON','Jnr Choi','TO THE MOON',2012,197);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (129,'Dreamer','Astelle','Dreamer',2011,171);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (130,'Left and Right (Charlie Puth) [feat. Jung Kook of BTS] - Sped Up Version','sped up nightcore','Left and Right (Charlie Puth) [feat. Jung Kook of BTS] [Sped Up Version]',2016,252);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (131,'Pepas','YES YES','Pepas',2016,295);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (132,'Bam Bam (feat. Ed Sheeran)','Camila Cabello','Familia',2020,222);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (133,'Fever - Remix','XY&O','Fever (Remix)',2011,291);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (134,'On My Way!','P.S.','On My Way!',2013,230);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (135,'Another Love','Tom Odell','Long Way Down (Deluxe)',2015,274);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (136,'Frozen','Madonna','Frozen',2014,233);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (137,'Riptide','Viva La Panda','Riptide',2014,228);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (138,'Down Under (feat. Colin Hay)','Luude','Down Under (feat. Colin Hay)',2014,183);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (139,'Meet Me At Our Spot','THE ANXIETY','THE ANXIETY',2012,297);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (141,'That Bxtch','Taylor Watson','That Bxtch',2017,271);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (142,'Long Road','HotBlock Jmoe','Long Road',2016,260);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (143,'Without You','John De Sohn','Without You',2010,277);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (144,'Light Switch','Charlie Puth','Light Switch (Instrumental)',2019,190);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (145,'I Wanna Know','Alex Alexander','I Wanna Know',2018,211);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (146,'1, 2, 3 (feat. Jason Derulo & De La Ghetto)','Sofía Reyes','1, 2, 3 (feat. Jason Derulo & De La Ghetto)',2015,236);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (147,'credit union','Kinrose','credit union',2010,181);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (148,'love nwantiti (ah ah ah)','CKay','CKay The First',2018,175);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (149,'Bad Habits','Ed Sheeran','Bad Habits',2016,200);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (150,'Leap of Faith','Alex Alexander','Leap of Faith',2019,238);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (151,'Ocean Eyes','Farux','Ocean Eyes',2017,206);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (152,'Chaa Chaa Chaa (feat. HoodCelebrityy)','Girll Codee','Chaa Chaa Chaa (feat. HoodCelebrityy)',2018,261);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (154,'Moi... Lolita','Monaldin','Moi... Lolita',2010,172);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (155,'Warning / Signs','Matvey Emerson','Warning / Signs',2012,270);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (156,'Serenity','Shab','Serenity',2019,215);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (157,'MAMIII','Becky G','MAMIII',2012,285);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (158,'Running To You (feat. Caden)','VINAI','Running To You (feat. Caden)',2017,193);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (159,'Good Morning','P.S.','Good Morning',2010,285);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (160,'MONTERO (Call Me By Your Name)','Lil Nas X','MONTERO (Call Me By Your Name)',2018,176);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (161,'Tainted Love','Thatsimo','Tainted Love',2014,167);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (162,'Build a Bitch','Bella Poarch','Build a Bitch',2010,213);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (163,'SAD GIRLZ LUV MONEY Remix (feat. Kali Uchis and Moliy)','Amaarae','SAD GIRLZ LUV MONEY Remix (feat. Kali Uchis and Moliy)',2013,263);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (165,'THATS WHAT I WANT','Lil Nas X','MONTERO',2014,252);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (166,'We Know','JAM & Philly','We Know',2010,162);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (167,'Cold Heart - PNAU Remix','Elton John','The Lockdown Sessions',2015,209);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (168,'Jiggle Jiggle','Duke & Jones','Jiggle Jiggle',2015,245);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (169,'Lost','Frank Ocean','channel ORANGE',2017,226);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (170,'Would I Lie to You','MISERO','Would I Lie to You',2014,205);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (172,'Life Goes On','Oliver Tree','Ugly is Beautiful: Shorter, Thicker & Uglier (Deluxe)',2014,194);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (173,'Dinero','Trinidad Cardona','Dinero',2012,295);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (174,'Pieces','Nippandab','Pieces',2012,287);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (175,'Pope Is a Rockstar','SALES','SALES LP',2012,211);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (176,'Looking for Love','Asketa & Natan Chaim','Looking for Love',2010,205);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (177,'edamame (feat. Rich Brian)','bbno$','edamame (feat. Rich Brian)',2019,274);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (178,'I Hate U','SZA','I Hate U',2017,186);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (179,'She Wolf (Falling to Pieces)','YES YES','She Wolf (Falling to Pieces)',2017,282);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (180,'Memories','Coopex','Memories',2017,289);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (181,'Ameno Amapiano Remix (You Wanna Bamba)','Goya Menor','Ameno Amapiano Remix (You Wanna Bamba)',2018,237);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (182,'Say My Name','Why Not','Say My Name',2010,292);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (183,'Woman','Doja Cat','Planet Her',2018,151);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (184,'Leave The Door Open','Bruno Mars','Leave The Door Open',2020,253);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (185,'I AM WOMAN','Emmy Meli','I AM WOMAN',2018,212);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (186,'Paint It Black','Dame Dame','Paint It Black',2018,152);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (187,'Vacation','Dirty Heads','Vacation',2020,187);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (188,'Free Falling Love','Lucas Estrada','Free Falling Love',2010,251);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (189,'Ocean Drive','Harddope','Ocean Drive',2020,173);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (190,'Kiss Me More (feat. SZA)','Doja Cat','Kiss Me More (feat. SZA)',2019,162);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (192,'The Hills','Farux','The Hills',2020,178);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (193,'Young Folks','Jungle Jonsson','Young Folks',2013,211);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (194,'good 4 u','Olivia Rodrigo','SOUR',2012,202);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (195,'Complicated','Nito-Onna','Complicated',2015,250);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (196,'Jalebi Baby (Tesher x Jason Derulo)','Tesher','Jalebi Baby (Tesher x Jason Derulo)',2016,200);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (198,'Talking to the Moon','Bruno Mars','Doo-Wops & Hooligans',2019,196);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (199,'Say It Right','MØRFI','Say It Right',2014,193);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (200,'Astronaut In The Ocean','Masked Wolf','Astronaut In The Ocean',2014,280);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (201,'Creep','Naeleck','Creep',2013,167);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (202,'Counting Stars','Farux','Counting Stars',2013,280);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (203,'Buss It','Erica Banks','Buss It',2010,217);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (204,'When You Were Young','Amero','When You Were Young',2018,270);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (205,'Apologize','Farux','Apologize',2019,222);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (206,'Beauty And A Beat','Glamii','Beauty And A Beat',2016,244);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (207,'Why','Padé','Why (with WLHELMINA)',2014,290);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (208,'Better Days (NEIKED x Mae Muller x Polo G)','NEIKED','Better Days (NEIKED x Mae Muller x Polo G)',2017,227);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (209,'The Motto','Tiësto','The Motto',2016,204);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (210,'Need to Know','Doja Cat','Planet Her',2020,165);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (211,'Whatever You Like','DLAY','Whatever You Like',2015,231);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (212,'MONEY','LISA','LALISA',2012,171);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (213,'Freaks','Surf Curse','Freaks',2018,293);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (214,'Heart of Glass','Nito-Onna','Heart of Glass',2016,300);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (215,'Blinding Lights','The Weeknd','After Hours',2011,264);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (216,'Thot Shit','Megan Thee Stallion','Thot Shit',2010,296);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (217,'Mr. Saxobeat','Nito-Onna','Mr. Saxobeat',2013,262);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (218,'Moves Like Jagger','Timemachine','Moves Like Jagger',2018,207);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (219,'Pumped Up Kicks','Madism','Pumped Up Kicks',2015,181);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (220,'Beautiful Mistakes (feat. Megan Thee Stallion)','Maroon 5','JORDI (Deluxe)',2020,160);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (221,'RAPSTAR','Polo G','RAPSTAR',2013,162);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (222,'Lies','Dame Dame','Lies',2019,201);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (223,'Ready 4 Luv - TMLH Summer Mix','CAZZETTE','Ready 4 Luv (TMLH Summer Mix)',2011,224);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (225,'Wellerman - Sea Shanty / 220 KID x Billen Ted Remix','Nathan Evans','Wellerman (Sea Shanty / 220 KID x Billen Ted Remix)',2015,169);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (226,'So Pretty','Reyanna Maria','So Pretty',2016,222);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (227,'Todo De Ti','Rauw Alejandro','Todo De Ti',2015,165);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (228,'Write This Down (Instrumental)','SoulChef','Escapism: Instrumentals',2010,173);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (229,'Peaches (feat. Daniel Caesar & Giveon)','Justin Bieber','Justice',2017,239);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (230,'positions','Ariana Grande','positions',2018,214);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (231,'Slow Down','Coopex','Slow Down',2010,228);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (232,'What If','HOURS','What If',2017,249);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (233,'Running Away','VANO 3000','Running Away',2013,185);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (234,'Aesthetic','Xilo','Aesthetic',2014,150);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (235,'Levitating (feat. DaBaby)','Dua Lipa','Future Nostalgia',2018,252);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (236,'Work from Home','Coopex','Work from Home',2020,158);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (237,'Bundles (feat. Taylor Girlz)','Kayla Nicole','Bundles (feat. Taylor Girlz)',2010,282);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (238,'Sweater Weather','The Neighbourhood','I Love You.',2010,225);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (239,'As It Was','Michael Shynes','As It Was',2010,193);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (240,'Follow Me','Senhit','Follow Me',2016,180);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (241,'Calling My Phone','Lil Tjay','Calling My Phone',2016,292);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (242,'Wicked Game','YES YES','Wicked Game',2011,263);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (243,'You Right','Doja Cat','Planet Her',2012,257);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (244,'Whoopty','CJ','Whoopty',2012,235);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (245,'Electric Love','BØRNS','Dopamine',2010,245);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (246,'When Hello Means Goodbye','Alex Alexander','On My Way',2014,266);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (247,'More Than A Woman - From "Saturday Night Fever" Soundtrack','Bee Gees','How Can You Mend A Broken Heart',2015,174);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (248,'Friday (feat. Mufasa & Hypeman) - Dopamine Re-Edit','Riton','Friday (feat. Mufasa & Hypeman) [Dopamine Re-Edit]',2012,181);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (249,'Hawái','Maluma','PAPI JUANCHO',2020,223);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (250,'Mood (feat. iann dior)','24kGoldn','Mood (feat. iann dior)',2013,191);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (251,'Paid','Astelle','Paid',2017,157);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (252,'drivers license','Olivia Rodrigo','drivers license',2013,292);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (253,'Lemonade','Internet Money','Lemonade (feat. Gunna, Don Toliver & NAV)',2012,150);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (254,'K Boy Bye','Astelle','K Boy Bye',2018,203);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (255,'Up','Cardi B','Up (Instrumental)',2010,234);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (256,'Just The Two of Us','Kauai45','Just The Two of Us',2018,258);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (257,'Play With Me','Ana Shine','Play With Me',2011,191);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (258,'Best Friend (feat. Doja Cat)','Saweetie','Best Friend (feat. Doja Cat) [Remix EP]',2014,237);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (260,'Forever','Nadia Gattas','Forever',2010,219);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (261,'The Business','Tiësto','The Business',2019,268);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (262,'telepatía','Kali Uchis','Sin Miedo (del Amor y Otros Demonios) ∞',2014,298);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (263,'Gravity (feat. Tyler, The Creator)','Brent Faiyaz','Gravity (feat. Tyler, The Creator)',2017,197);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (264,'motive (with Doja Cat)','Ariana Grande','Positions (Deluxe)',2013,205);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (265,'Feel Your Love','Yusuf Alev','Feel Your Love',2016,282);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (266,'Lost on You','sad girls','Lost on You',2016,272);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (267,'Good Days','SZA','Good Days',2020,170);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (268,'What You Know Bout Love','Pop Smoke','Shoot For The Stars Aim For The Moon',2013,165);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (269,'Rude Boy','YES YES','Rude Boy',2020,209);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (270,'WAP (feat. Megan Thee Stallion)','Cardi B','WAP (feat. Megan Thee Stallion)',2019,291);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (271,'Savage Love (Laxed - Siren Beat)','Jawsh 685','Savage Love (Laxed - Siren Beat)',2016,200);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (272,'dirty laundry','blackbear','deadroses',2013,289);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (273,'HOLIDAY','Lil Nas X','HOLIDAY',2017,290);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (274,'WITHOUT YOU','The Kid LAROI','F*CK LOVE (SAVAGE)',2015,281);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (276,'ROCKSTAR (feat. Roddy Ricch)','DaBaby','BLAME IT ON BABY',2015,183);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (277,'34+35','Ariana Grande','Positions',2012,200);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (278,'Rover (feat. DTG)','S1mba','Rover (feat. DTG)',2017,292);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (279,'Put Your Records On','Ritt Momney','Put Your Records On',2018,277);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (280,'Mood Swings (feat. Lil Tjay)','Pop Smoke','Shoot For The Stars Aim For The Moon',2020,204);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (281,'Therefore I Am','Billie Eilish','Therefore I Am',2017,254);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (282,'Wild & Free','Nander','Wild & Free',2018,277);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (283,'Glad You Came','Braaheim','Glad You Came',2010,296);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (284,'For The Night (feat. Lil Baby & DaBaby)','Pop Smoke','Shoot For The Stars Aim For The Moon',2013,276);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (285,'Backyard Boy','Claire Rosinkranz','BeVerly Hills BoYfRiEnd',2017,150);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (286,'TKN (feat. Travis Scott)','ROSALÍA','TKN (feat. Travis Scott)',2013,213);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (287,'Say It Right','Coopex','Say It Right',2020,237);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (288,'Without You','Baby Bluu','Without You',2012,209);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (289,'Play Date','Melanie Martinez','Cry Baby (Deluxe Edition)',2015,189);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (290,'Freak','Doja Cat','Freak',2019,296);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (291,'Falling Down','Andrew Nagy','Falling Down',2019,172);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (292,'Wait a Minute!','WILLOW','ARDIPITHECUS',2010,279);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (293,'Banana (feat. Shaggy) - DJ FLe - Minisiren Remix','Conkarah','Banana (feat. Shaggy) [DJ FLe - Minisiren Remix]',2020,268);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (294,'Over You','Myrrhe','Over You',2016,181);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (295,'FLIP THE SWITCH (feat. Drake)','Quavo','QUAVO HUNCHO',2018,184);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (296,'The Boss','Coopex','The Boss',2010,257);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (297,'Party Girl','StaySolidRocky','Party Girl',2015,250);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (298,'Love Me Again','CPX','Love Me Again',2014,278);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (299,'Renee','SALES','Renee',2013,250);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (301,'Right Here Waiting','Boostereo','Right Here Waiting',2013,201);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (302,'THE SCOTTS','THE SCOTTS','THE SCOTTS',2012,204);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (304,'Kiss Me','Lucas Estrada','Kiss Me',2020,190);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (305,'Red Flag','Pia Baris','Red Flag',2012,253);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (306,'One too Many Times','JRL','One Too Many Times',2010,209);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (308,'Boss Bitch','Doja Cat','Boss Bitch',2015,219);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (309,'Only Girl','Coopex','Only Girl',2020,289);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (310,'Tap In','Saweetie','Tap In',2020,254);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (311,'Forever','Gianni Blu','Forever',2010,192);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (312,'Rather Be','Cabuizee','Rather Be',2011,295);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (313,'Savage','Megan Thee Stallion','Suga',2014,215);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (314,'Blueberry Faygo','Lil Mosey','Certified Hitmaker',2020,170);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (315,'Break My Heart','Dua Lipa','Future Nostalgia',2011,179);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (316,'On My Way','Alex Alexander','On My Way',2017,169);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (317,'Astronomia','Vicetone','Astronomia',2014,195);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (318,'The Box','Roddy Ricch','Please Excuse Me for Being Antisocial',2018,189);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (320,'Supalonely','BENEE','STELLA & STEVE',2017,214);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (321,'Toosie Slide','Drake','Dark Lane Demo Tapes',2016,240);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (323,'Be Kind (with Halsey)','Marshmello','Be Kind (with Halsey)',2019,231);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (324,'Intentions (feat. Quavo)','Justin Bieber','Changes',2011,245);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (325,'Old Times','Xtinctor','Old Times',2010,169);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (326,'Hey, Soul Sister','LANDR','Hey, Soul Sister',2019,259);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (327,'Later Bitches','The Prince Karma','Later Bitches',2013,187);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (328,'Life Is Good (feat. Drake)','Future','Life Is Good (feat. Drake)',2016,163);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (329,'WHATS POPPIN','Jack Harlow','WHATS POPPIN',2010,248);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (330,'Let Her Go','LANDR','Let Her Go',2010,261);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (331,'Sunday Best','Surfaces','Where the Light Is',2012,298);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (332,'DÁKITI','Dame Dame','DÁKITI',2018,216);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (333,'Say So','Doja Cat','Hot Pink',2018,151);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (334,'In Your Eyes','The Weeknd','After Hours',2015,182);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (335,'Falling','Trevor Daniel','Falling',2019,235);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (336,'Let It Go','Dame Dame','Let It Go',2019,236);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (337,'death bed (coffee for your head)','Powfu','death bed (coffee for your head)',2011,258);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (338,'That Way','Lil Uzi Vert','That Way',2016,151);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (340,'BOP','DaBaby','KIRK',2012,173);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (341,'OUT WEST (feat. Young Thug)','JACKBOYS','JACKBOYS',2019,203);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (342,'Blinding Lights','The Weeknd','Blinding Lights',2018,264);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (343,'When the Sun Goes Down','Martin van Lectro','When the Sun Goes Down',2011,284);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (344,'Skechers','DripReport','Skechers',2020,223);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (345,'ROXANNE','Arizona Zervas','ROXANNE',2015,173);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (346,'Shooting Stars','Bag Raiders','Bag Raiders (Deluxe)',2013,155);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (347,'The Git Up','Blanco Brown','The Git Up',2013,155);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (348,'Payphone','Faruk Orman','Payphone',2019,260);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (350,'hot girl bummer','blackbear','hot girl bummer',2016,183);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (351,'Demons','CPX','Demons',2020,218);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (352,'Girls Like You (feat. Cardi B) - Cardi B Version','Maroon 5','Red Pill Blues (Deluxe)',2020,263);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (353,'Without Me','Halsey','Without Me',2018,265);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (354,'Plug Walk','Rich The Kid','The World Is Yours',2013,200);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (355,'California Dreaming','Jorm','California Dreaming',2018,158);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (356,'Rockstar','Ilkay Sencan','Rockstar',2011,181);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (357,'Falling for U','Peachy!','Falling for U',2012,279);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (358,'Lovely','Alfons','Lovely',2013,168);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (359,'The Less I Know The Better','Tame Impala','Currents',2014,257);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (360,'Dandelions','Ruth B.','Safe Haven',2020,188);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (361,'Jimmy Cooks (feat. 21 Savage)','Drake','Honestly, Nevermind',2010,270);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (362,'Good Looking','Suki Waterhouse','Good Looking',2016,292);
INSERT INTO songs(sid,title,artist,album,year,durationsec) VALUES (363,'INFERNO','Sub Urban','INFERNO',2020,223);
